version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: python3
    working_dir: /app
    tty: true
    volumes:
      - .:/app

  mysql:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '**********'
      MYSQL_DATABASE: '**********'
      MYSQL_USER: '**********''
      MYSQL_PASSWORD: '**********'

volumes:
  db-data: