version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: python3
    working_dir: /app
    tty: true
    volumes:
      - .:/app

  mysql:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '**********'
      MYSQL_DATABASE: '**********'
      MYSQL_USER: '**********'
      MYSQL_PASSWORD: '**********'

  phpmysadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - 8088:80
    depends_on:
      - mysql
    restart: always

volumes:
  db-data: